version: '3'

services:
  web:
    image: weather-web
    build: nginx
    ports:
      - "80:80"
  weather-front:
    image: weather-frontend
    build: app
    ports:
      - "3000:3000"
  weather-api:
    image: weather-api
    build: server
    ports:
      - "3001:3001"
